### ISSUE TITLE
Diverse Smartblocks: Aktualisierung des Alias erfolgt nur bei manuellem Reload der Seite

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#1006]
Ich bin nicht sicher, ob es ein wirklicher Bug oder ein Enhancement wäre.
Bei einigen Smartblocks (siehe Liste) aktualisieren die erzeugten Alias-Blöcke erst, wenn man die Seite manuell neu lädt.

- [ ] Anhang: Dateiliste im Alias aktualisiert erst nach Reload der Seite oder nach Wechsel zw. Liste/Tabelle
- [ ] Akkordeon 
- [ ] Spalten
- [ ] Tabelle

**Comment by pmdevelopment** [comment]
Das ist prinzipiell ein Feature Request, der vermutlich noch nicht relevant wurde, weil üblicherweise kein Alias auf der Seite mit dem originalen Block liegt. Betrifft auf jeden Fall alle SmartBlocks, das ist bisher für keinen vorgesehen.
