### ISSUE TITLE
Smartblock Spalten: Fehlerhafte Darstellung vers. eingefügter Inhalte 

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#1007]
Das Einfügen verschiedener Smartblocks in das Spalten-Modul führt zu einer unschönen Darstellung dieser. Einige Beispiele siehe Screenshots.
Hier sollte ggf. implementiert werden, dass nur einige Smartblocks zum Einfügen in Spalten zur Verfügung stehen. Komplexer wäre es noch, verschiedene Smartblocks nur für eine bestimmte Spaltenanzahl verfügbar zu machen. 
@LisaS13, das müsste man mal ausgestalten..

- [x] Ansprechperson: Spalte mit Hintergrundfarbe geht nicht über die gesamte Breite
![Bildschirmfoto 2024-08-06 um 10 44 34](https://github.com/user-attachments/assets/16e3f75c-6259-4bb4-bd66-6d32a489339d)
--> Unter "Schnelles bearbeiten" muss die Checkbox "Hintergrundfarbe über die gesamte Breite anzeigen." angeklickt werden

#1026
![Bildschirmfoto 2024-08-06 um 10 30 32](https://github.com/user-attachments/assets/9f37641e-2af3-4783-ae80-377cadce6edb)

#1027
- [ ] CTA: Text im Button nicht lesbar > ggf. Beschreibungstext darüber/darunter anordnen? 
- [ ] Überschrift: wird nicht getrennt sondern abgeschnitten 
![Bildschirmfoto 2024-08-06 um 11 16 16](https://github.com/user-attachments/assets/20539513-f906-4c29-a026-d64e0ee5f74a)
- [ ] Audio:
![Bildschirmfoto 2024-07-30 um 08 33 02](https://github.com/user-attachments/assets/06ea1ee6-0443-4e83-8517-554c606c865a)

**Comment by ChristinaGu** [comment]
Hinweis-Modul bei Smart-Blocks, die für Spalten zu schmal sind, siehe Figma-Embed
