### ISSUE TITLE
Diverse SmartBlocks: Kommentarfunktion global entfernen

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#1008]
Meines Wissens sollte die Kommentarfunktion nicht mehr vorhanden sein, in folgenden Modulen ist sie bei der Bearbeitung der Smartblocks noch sichtbar: 

- [x] UI Pattern
- [x] Kontakt
- [x] Code 
- [x] Icons
- [x] Farben

 Bitte prüfen das Kommentarfunktion in Inspiration Smart-Tool weiterhin funktioniert.

**Comment by pmdevelopment** [comment]
Es gibt legacy SmartBlocks, die noch nicht auf die neue "Quick Edit" Funktion aktualisiert sind und beim anlegen/bearbeiten die Seite wechseln, die müssen noch überarbeitet werden und verlieren die Kommentarfunktion dabei automatisch
