### ISSUE TITLE
SmartBlock Kontakt: Button verschwindet im Spalten-Modul

### ISSUE THREAD

**Issue by Kschneider94** [wirDesign-communication-AG/wirhub-app#1026]
Im Spalten-Modul: Verändert man die Anzahl der Spalte verschwindet der angelegte Button
![Bildschirmfoto 2024-08-06 um 10 30 32](https://github.com/user-attachments/assets/9f37641e-2af3-4783-ae80-377cadce6edb)

**Comment by jholtkoetter** [comment]
Kann ich nicht reproduzieren, scheint bereits behoben zu sein. @lisaschreyer Kannst du das bestätigen?

**Comment by lisaschreyer** [comment]
@jholtkoetter - ja, kann ich auch nicht mehr reproduzieren. Passt dann so aus meiner Sicht!
