### ISSUE TITLE
SmartBlock Hinweis: Inline-Toolbar fehlt im Spalten-Block

### ISSUE THREAD

**Issue by Kschneider94** [wirDesign-communication-AG/wirhub-app#1033]
--> Wenn man den Hinweis-Block in einer 2/3 Breite eingestellt hat und in ein Spalten-Modul dupliziert, entfällt die Inline-Funktion "Breite" und man kann den Hinweis nicht mehr auf die volle Breite setzen.
--> Screenshot Testing:<img width="1168" alt="Bildschirmfoto 2024-09-06 um 13 40 20" src="https://github.com/user-attachments/assets/326cf1e3-795a-4fb9-aa6a-16d3a13a3035">
Design: https://www.figma.com/design/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?node-id=1088-435

**Comment by pmdevelopment** [comment]
Korrekte Lösung: wird der Hinweis in eine Column eingefügt, werden 100% Breite erzwungen
