### ISSUE TITLE
Login und Registrierung in der Höhe nicht scrollbar

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#1038]
Wenn die Login Und Registrierungsseite in einem flachen Browserfenster geöffnet werden, werden sie angeschnitten.
Betrifft mindestens:

- Login-Seite

- Passwort Erstellen

- Registrierungsformular

<img width="1854" alt="Bildschirmfoto 2024-09-12 um 09 24 56" src="https://github.com/user-attachments/assets/56d9d3eb-cd83-4772-a8d3-a16fe972a13f">

**Comment by pmdevelopment** [comment]
` justify-content-center align-items-center` durch `overflow-auto` ersetzen; `margin:auto;` für den inneren `DIV`
