### ISSUE TITLE
SmartBlock Farben: Einstellungen sind nicht vorhanden

### ISSUE THREAD

**Issue by Kschneider94** [wirDesign-communication-AG/wirhub-app#1042]
Die Einstellungen des Blocks fehlen (Zusätzliche Felder, HEX und RGB-Wert ausblenden, Zeige Farbabstufungen (75%/50%/25%)).

Beispiel wo es fehlt, v3.0.33.1:
<img width="1082" alt="Bildschirmfoto 2024-09-18 um 11 16 58" src="https://github.com/user-attachments/assets/574cb051-6bf7-4d75-8a86-a88ffc21139e">

Beispiel BVR, die noch auf v3.0.20.1 laufen:
<img width="463" alt="Bildschirmfoto 2024-09-18 um 11 06 27" src="https://github.com/user-attachments/assets/ef47b2d0-4b75-45af-9656-7cea8030b6c4">
<img width="1136" alt="Bildschirmfoto 2024-09-18 um 11 06 33" src="https://github.com/user-attachments/assets/f44d1df4-0c75-4b6c-a846-794ffa42cd5e">

**ToDo's:**
- [x] Edit-Funktion wieder ergänzen

**Comment by pmdevelopment** [comment]
Lösung per Inline-Edit
