### ISSUE TITLE
Feature-Tour zum Inline-Editing der Farben

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#1081]
Sollten wir das nicht featuren @LisaS13 ?

**Comment by LisaS13** [comment]
Yes, sollten wir!

**Comment by pmdevelopment** [comment]
![10_Color_960x540](https://github.com/user-attachments/assets/726d9c6e-db4b-42a4-b791-88fd12e9fb3a)

**Comment by pmdevelopment** [comment]
Farben
Wir haben unseren Farben Smart-Block überarbeitet! Ab sofort können die Farben direkt in den Kacheln hinzugefügt werden. Dank des neuen Text-Editors muss man nur in die Kachel klicken und kann sofort die gewünschte Farbe wählen und anwenden.

Colors
We have updated our Color Smart-Block! From now on, colors can be added directly to the cards. Thanks to the new text editor, you only have to click in the textfields and can immediately select and apply the desired colour.

**Comment by LisaS13** [comment]
V2 des Bildes!

[Image](https://github.com/user-attachments/assets/d25d8f30-4020-4807-bdaa-ed60b053ef15)
