### ISSUE TITLE
CKEditor zeigt Label

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#1099]
In den Textfeldern wird das CKEditor-Label wieder angezeigt.

![Bildschirmfoto 2024-12-10 um 08 29 12](https://github.com/user-attachments/assets/42535923-949c-43dd-b760-e09df52ffa6a)

**Comment by pmdevelopment** [comment]
Lösung erforderte

- Aktualisierung des Lizenz-Keys in `assets/ckeditor5/editor-smart-block.js`
- Aktualisierung des Editors auf die neuste Version in `assets/ckeditor5/package.json`
