### ISSUE TITLE
SmartBlock Inhaltsverzeichnis: Ausgeblendete Überschriften

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#1111]
Rolle: Editor / v.3.0.40.1

- [ ] Ausgeblendete Überschriften werden im Inhaltsverzeichnis der Seite mit ausgegeben; Annahme: sobald ich eine Überschrift ausblende, ist diese auch nicht mehr im Inhaltsverzeichnis zu sehen

**Comment by pmdevelopment** [comment]
Duplikat von #987
