### ISSUE TITLE
SmartBlock Code: Darstellungsfehler bei Ausblendung

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#1116]
Rolle: Editor / Version: v3.0.40.1

- [x] bei ausgeblendetem SmartBlock tritt ein Darstellungsfehler aus (dasselbe bei SmartBlock UI Pattern #995)
<img width="1047" alt="Bildschirmfoto 2024-12-18 um 11 33 11" src="https://github.com/user-attachments/assets/f03c2dc5-608e-4a0a-a3c2-a557cd0ed9ae" />

**Comment by pmdevelopment** [comment]
Das ist ein wontfix, im Zuge der Überarbeitung des SmartBlocks wird der Coode-Editor ausgetauscht und damit das Problem gelöst.
