### ISSUE TITLE
SmartBlock Slider: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#113]
- [x] Wenn man nach links ein neues Bild hinzufügt, wird nicht auf das neue Bild gesprungen, sondern man sieht das noch das alte Bild. Beim rechts einfügen springt es zum neuen Bild
- [x] Slides auf 10 Slides begrenzen
- [x] Für das Hinzufügen neuer Slides bitte folgendes Icon anstelle von dem + verwenden: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aadd_photo_alternate%3A
- [x] ~~Wenn nur Slideshows auf der Seite liegen, können diese im Quick-Edit nicht verschoben werden~~
- [x] ~~Sortieren über "Pfeil links", "Pfeil rechts" in der Toolbar ergänzen~~

**Comment by pmdevelopment** [comment]
" Wenn nur Slideshows auf der Seite liegen, können diese im Quick-Edit nicht verschoben werden"

Wo kann ich das reproduzieren? Lässt sich für mich nicht nachvollziehen.

**Comment by pmdevelopment** [comment]
"Sortieren über "Pfeil links", "Pfeil rechts" in der Toolbar ergänzen"

Den Punkt ist unklar.
