### ISSUE TITLE
SmartBlock Anhang: Datei-Informationen

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirhub-app#154]
Durch lange Dateinamen kann man nicht mehr sehen, was für eine Endung die Datei hat.
Es wäre hilfreich, wenn man zusätzlich zu dem Namen noch den Dateitypen sieht und das Upload-Datum.
@ChristinaGu das war zuletzt auch Feedback in den Interviews fürs Markenportal. 

**Design:**
https://share.goabstract.com/9ad22819-8f44-4bca-85c8-03967dd72eee?collectionLayerId=d1369696-8150-473f-8a6c-3d0b30049cb7&mode=design

**Job:** 2WD

**Comment by ChristinaGu** [comment]
Du kannst ja mal einen Designvorschlag machen. Fände es aber besser wenn auf hover einfach der volle Dateiname als Toolptip zu sehen ist

**Comment by laurahll** [comment]
https://share.goabstract.com/9ad22819-8f44-4bca-85c8-03967dd72eee?collectionLayerId=d1369696-8150-473f-8a6c-3d0b30049cb7&mode=design @ChristinaGu
VKB war der Name der Datei ja wichtig. Ich finde die Dateiart aber auch auf den ersten Blick wichtig. oft liegen da gleich benannte dateien in anderen formaten.
"Stand" würde sich aktualisieren, wenn die datei hochgeladen wird oder der name verändert. macht das sinn, oder lieber "Hochgeladen am..."?

**Comment by laurahll** [comment]
Ich hab noch eine erweiterte Version gemacht. FALLS wir das als auftrag bei VKB durchkriegen sollten :D
Wäre mit der Vorschau bestimmt umfangreicher.
https://share.goabstract.com/9ad22819-8f44-4bca-85c8-03967dd72eee?collectionLayerId=2172947e-234f-467e-bb28-d1e08723650f&mode=design
![image](https://user-images.githubusercontent.com/66866462/152762521-5aff97d5-40ed-4393-a51b-7313bbc4cf40.png)

**Comment by ChristinaGu** [comment]
Wurde über Tooltip gelöst
