### ISSUE TITLE
QuickEdit: Modul Auswahl

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirhub-app#157]
Manchmal ist es schwer die Toolbar von Spalten auszuwählen, weil es zu schnell zwischen der Spalten-Toolbar und der Toolbar der Module in den Spalten springt (1). Mein Workaround ist, im Fenster zu Zoomen, damit die Toolbar größer wird. (2)
Könnten wir vielleicht noch in der Verschieben-Liste (3) ein icon hinzufügen, durch das man in den Quick Edit mode von dem Modul springt? Ich finde das Stift Icon auch verwirrend, weil man es dort umbenennt anstatt bearbeitet.

(1)
![image](https://user-images.githubusercontent.com/66866462/142191445-b3005a33-3dda-4cd8-b7ed-c6d3a04d9ecf.png)
(2)
![image](https://user-images.githubusercontent.com/66866462/142191887-cd2de69e-6205-4072-8287-db89ad905b24.png)
(3)
![image](https://user-images.githubusercontent.com/66866462/142192021-e92b1914-89fd-44d2-ba36-164db0e96c8d.png)

**Comment by ChristinaGu** [comment]
Den Gedanken hatte ich auch schon. V.a. weil ich glaube die Umbenennen Funktion wird ohnehin nicht genutzt oder?

**Comment by laurahll** [comment]
Ich hab sie tatsächlich noch nie benutzt
