### ISSUE TITLE
SmartBlock Do/Dont: Mit Rich Text erweitern

### ISSUE THREAD

**Issue by laurahll** [wirDesign-communication-AG/wirhub-app#181]
Bisher steht zu den Einträgen bei dem Do Dont Smartblock nur ein einfaches Input Feld. Es wäre sehr hilfreich, wenn man dort den Rich Text Editor hätte, u.a. durch Aufzählungen.
Kann man bei dem Editor auch Optionen disablen?

**Comment by pmdevelopment** [comment]
Wichtig: nur mit Umbau auf inline editing

**Comment by pmdevelopment** [comment]
Wird in #818 behandelt
