### ISSUE TITLE
Datei-Berechtigungen im Hilfe-Menü validieren

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#185]
Abgleich der in der Installations-Dokumentation beschriebenen Ordner

- [x] ob der Benutzer identisch zum aktuellen Benutzer des Webservers ist. 
- [x] ob die Ordner beschreibbar sind

**Comment by ChristinaGu** [comment]
Ist das nicht bereits umgesetzt?
