### ISSUE TITLE
Smartblock Text: "Quote" ist nicht gestylt

### ISSUE THREAD

**Issue by nkalinowskiwd** [wirDesign-communication-AG/wirhub-app#229]
Setze ich einen Text als "Quote" ein, wird dieser im Frontend nicht gestylt und hebt sich daher nicht vom Fließtext ab. Im Quellcode wird er als <blockquote> gerendert.

**Comment by ChristinaGu** [comment]
Hi Laura, 
könntest du dir mal Gedanken zu einem einfachen <blockquote> Style machen, dass erst mal für alle wirHubs funktioniert? 

Mach dir gerne auch Gedanken dazu welche Variablen es geben müsste um das Blockquote für die einzelnen Marken anzupassen. 

Merci :)

**Comment by ChristinaGu** [comment]
Hinfällig, da CKEditor
