### ISSUE TITLE
Smartblock Bild: Textstyle prüfen wenn Link auf ganzes Element gesetzt ist

### ISSUE THREAD

**Issue by nkalinowskiwd** [wirDesign-communication-AG/wirhub-app#231]
Wird ein Link auf den Smartblock gesetzt, wird der Text als Link gestylt. Ist das gewünscht? Schöner wäre, wenn der Text wie Fließtext gestylt ist und nur Links, die im CK Editor gesetzt wurden, als Link gestylt sind. 

<img width="1092" alt="sb-bild-link" src="https://user-images.githubusercontent.com/98943318/152317258-aa648275-d804-44da-84c2-efb3a5b1e574.png">

**Comment by ChristinaGu** [comment]
Nicht mehr reproduzierbar
