### ISSUE TITLE
Diverse Smartblöcke: Verlauf enthält leere Einträge

### ISSUE THREAD

**Issue by nkalinowskiwd** [wirDesign-communication-AG/wirhub-app#234]
Bei einigen Smartblöcken sind im Verlauf sind zwar Einträge mit Datum vorhanden, ich kann aber nicht sehen, was geändert wurde. 

**Betrifft:** 
- Teaser
- Bühne
- Do/Don't

Beispiel: https://kws-staging.wirhub.de/default/style/category/02-22 

<img width="1664" alt="sb-teaser-verlauf" src="https://user-images.githubusercontent.com/98943318/152359530-1634310c-2dfa-4273-ae01-34558772de4d.png">

**Comment by ChristinaGu** [comment]
Hinfällig. Feature gibt es nicht mehr
