### ISSUE TITLE
Smartblock Slideshow: Verlauf speichert Änderungen nicht

### ISSUE THREAD

**Issue by nkalinowskiwd** [wirDesign-communication-AG/wirhub-app#242]
Ich habe eine Slideshow angelegt und in verschiedenen Schritten, Bilder hinzugefügt, gelöscht und Text geändert. 

Im Verlauf sind diese Änderungen nicht abgebildet. Es ist lediglich die Version 1 vorhanden, welche "Angelegter Smartblock ohne Slides" ist.

Beispiel: https://kws-staging.wirhub.de/default/style/category/02-22#el_7859d308c8c3b_container

<img width="1366" alt="slideshow-verlauf" src="https://user-images.githubusercontent.com/98943318/152741381-0077905a-563b-444d-916b-4fe23d7c3f30.png">

**Comment by ChristinaGu** [comment]
Hinfällig. Feature existiert nicht mehr
