### ISSUE TITLE
SmartBlock Animation: Hinweis auf Dateiformat hinzufügen

### ISSUE THREAD

**Issue by nkalinowskiwd** [wirDesign-communication-AG/wirhub-app#281]
Beim SmartBlock Animation wird ein JSON verlangt. Es wäre gut, wenn im Reiter Inhalt beim Upload ein Hinweis zum erwarteten Dateiformat angezeigt wird.

**Comment by laurahll** [comment]
Ja, das ist gerade ganz oben auf meiner to do liste. Validierung zu dateiformaten ist in keinem modul richtig vorhanden.

**Comment by pmdevelopment** [comment]
Wurde mit dem Inline-Update gelöst.
