### ISSUE TITLE
Plugin: Logo-Creator

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#516]
**Design**
https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=2456-29446&t=SyDu4wXjh0dAnwbX-4

**Konzept**
[liegt hier ](https://wirdesignde.sharepoint.com/:f:/r/sites/FUCHSBrandportal/Freigegebene%20Dokumente/General/Logo%20Creator?csf=1&web=1&e=NeT9jv)

**Budget**
4 Tage

**Comment by pmdevelopment** [comment]
Offene Todos:

- [ ] SVG Fixen (image/svg+xml statt text/plain)
- [ ] Github Token im Repo hinterlegen
