### ISSUE TITLE
SmartBlock Text: Kein Style für Zitate

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#521]
Blockquotes haben keinen Style. K** nutzt bspw:

    /* Blockquote in text module */
    blockquote p {
        font-size: 2.5rem !important;
        color: $wd--color-brand;
        font-weight: 300 !important;
    }
    blockquote p::before {
        content: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIzLjAuMiwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkViZW5lXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAyMi4zIDE5LjciIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDIyLjMgMTkuNzsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiNGRjZDMDA7fQo8L3N0eWxlPgo8Zz4KCTxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik05LjYsOC41YzAsNS41LTEuMiwxMC05LjYsMTEuMnYtNC41YzMuMS0wLjQsNC4yLTIuMiw0LjMtNC45SDBWMGg5LjZWOC41eiBNMjIuMyw4LjVjMCw1LjUtMS4yLDEwLTkuNiwxMS4yCgkJdi00LjVjMy4xLTAuNCw0LjItMi4yLDQuMy00LjloLTQuM1YwaDkuNlY4LjV6Ii8+CjwvZz4KPC9zdmc+Cg==');
        display: inline-block;
        height: 30px;
        width: 30px;
        margin-right: 20px;
    }

**Comment by ChristinaGu** [comment]
Nicht mehr relevant durch CKEditor
