### ISSUE TITLE
SmartBlock Stage: Div für Text nur rendern, wenn Text enthalten

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#529]
Für FUCHS soll der Text auf der Stage auf der im CI geregelten Blue Box stehen. Das habe ich im SCSS entsprechend hinterlegt. Problem: der div wird auch dann ausgegeben, wenn kein Text in der Box enthalten ist. 

Bitte nach Möglichkeit so anpassen, dass .stage-text nur dann ausgegeben wird, wenn auch Text gepflegt wurde

**Comment by pmdevelopment** [comment]
#569 löst das Problem
