### ISSUE TITLE
Sidenav: individuelle Links im Sticky Footer berücksichtigen Translation nicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#541]
Es scheint so, als würde für jede Sprache der Titel der Default Sprache angezeigt werden.  Siehe BrandNet, hier wird auch bei Wechsel zu Deutsch, der englische Titel der Seite verwendet.

**Comment by pmdevelopment** [comment]
Betrifft ausschließlich verlinkte Seiten
