### ISSUE TITLE
Plugin: Media Creator v1.0

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#573]
**Design**
https://www.figma.com/file/j7Gl5Fsx0tyN8fKmqW796J/Smart-Tools?type=design&node-id=0-1&mode=design&t=EcfLaGHsjSB6jKta-0

**Budget**
10 Tage

# Offene Todos
- [x] Social-Media: Texte aus Chapter Teaser unter dem SmartTool übernehmen. Bei Formaten, die noch nicht fertig sind "Coming Soon" stehen lassen
- [x] Social-Media: Carousel entfernen
- [x] Products & Software - Copytext - Firefox kann unten rechts wählen
- [x] 9:16 Formate im Export fehlerhaft

# Abgeschlossen
## Teaser

- [x] Canto Integration
- [x] Maximale Anzahl Zeilen
- [x] Maximale Breite
- [x] "Back"-Button mit Confirmation versehen
- [x] Sidebar scrolling
- [x] 9:16 - Outlined Button falsch positioniert
- [x] 9:16 - Duffer höher
- [x] Einbindung in Columns unterbinden
- [x] Subline 3-Zeilig
- [x] 1:1 Button auch bei Textbox unverändert
- [x] Outline Button unten falsch positioniert

## Products And Software
- [x] Copytext als abweichende Inputs

## Webbanner
- [x] Formate umsetzen

## Global
- [x] Optionen initialisieren bei Varianten-Wechsel
- [x] Shortcuts in Contenteditable unterbinden!
- [x] "Close"-Icon wenn das Bild ersetzt wird
- [x] Bild per Canto beim 2. Versuch "403"

# Zurückgestellt

- [ ] Webbanner mit Zoom erstellen und dann runter skalieren
- [ ] Erhalt von Position/Zoom bei Wechsel zwischen Varianten
- [ ] Textbox und Text-Farbe voneinander abhängig machen

**Comment by Kschneider94** [comment]
**Feedback vom 08.03.2023** hier dokuemntiert:

https://teams.microsoft.com/l/message/19:893226e6554f4b7b9c0fb67ad2036ad1@thread.tacv2/1686296902102?tenantId=aeb9a5ed-4884-448b-814d-529c2e0f5072&groupId=7ffdb254-916d-435e-8327-d67803c459bd&parentMessageId=1686143495257&teamName=Balluff&channelName=wirHub&createdTime=1686296902102&allowXTenantAccess=false
