### ISSUE TITLE
SmartBlock Text: Inline Edit

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#623]
**ToDos**
- [x] Inline Edit implementieren, Spezifikation siehe Design
- [x] Edit-Button aus Toolbar entfernen

**Design**
https://www.figma.com/file/kpIVnqrNdJhZL1eAoEf2hm/Smartblocks?type=design&node-id=1%3A2&t=jNeEUVnMqMvL1K78-1

**Comment by pmdevelopment** [comment]
Notiz zur Umsetzung: Zur Vereinfachung wird die Toolbar vorerst auf Ballon Design vereinheitlicht.
