### ISSUE TITLE
SmartBlock Inhaltsverzeichnis

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#630]
**User Story** 
Als wirHub Redakteur möchte ich an beliebiger Stelle ein Inhaltsverzeichnis platzieren können, um Nutzer:innen eine besser Orientierung innerhalb der Seite zu gewährleisten. 

**Akzeptanzkriterien**
* Default werden die Links aus der Sprungmarken-Navigation übernommen
* Bei Bedarf können andere Links aus den auf der Seite vorhandnen Headlines gewählt werden

**Ausbaustufe**
* Redakteur kann zwischen verschiedenen Icons wählen
* Redakteur kann wählen, ob Icon links oder rechts
* Redakteur kann externe Links setzen

**Design**
tbd

**Comment by LisaS13** [comment]
Design: https://www.figma.com/file/kpIVnqrNdJhZL1eAoEf2hm/Smartblocks?type=design&node-id=412%3A7435&mode=design&t=O5SRE4s8tKf3N8sN-1

**Comment by pmdevelopment** [comment]
Fürs erste geschlossen, die Ausbaustufe darf einen neuen Task erhalten.
