### ISSUE TITLE
Guided Tour Beta: Onboarding für Inline-Edit

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#646]
Guided Tour für Inline-Edit, die zunächst statisch eingebaut wird und Editoren einmalig beim Wechsel in den Edit-Mode angezeigt wird. 

**Design**
https://www.figma.com/file/hmz3cNKTYTdrNQAwQBk1b3/Features?type=design&node-id=4-1185&mode=design&t=9PO5xZt4iutn1PzE-4

**Comment by pmdevelopment** [comment]
@Kschneider94
