### ISSUE TITLE
Seiten verwalten: wiederhergestellte Seiten automatisch als Entwurf

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#647]
**User Story** 
Als wirHub Redakteur möchte ich, dass eine von mir wiederhergestellte gelöschte Seite automatisch als Entwurf wiederhergestellt wird und bei Bedarf von mir veröffentlich werden muss.

**Comment by pmdevelopment** [comment]
Bei wirHubs die kein Approval Feature verwenden, sollte die Seite unsichtbar sein bei Wiederherstellung.
