### ISSUE TITLE
Smart-Block Icons: Begrenzung bei PNG-Größe mit Fehlermeldung abfangen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#664]
Aktuell ist es nicht möglich ein PNG in der Abmessung 4000x4000px herunterzuladen. 

- [ ] Prüfen wieso
- [ ] Falls Begrenzung technisch notwendig bitte beim Downloadversuch Fehlermeldung anzeigen "PNGs können nur bis zu einer Größe von XXpx heruntergeladen werden."

**Comment by pmdevelopment** [comment]
Limit auf 4.000 erhöht; Bug gefixed durch den der Fehler nicht angezeigt wurde.
