### ISSUE TITLE
Quick-Edit: Bug beim Ändern von Einstellungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#694]
![Bildschirmfoto 2023-09-04 um 16 30 27](https://github.com/wirDesign-communication-AG/wirhub-app/assets/8007132/d1205fee-9a6f-4547-ad6e-9c63bbf81ab4)

**Comment by pmdevelopment** [comment]
Ursache ist, dass zu dem Zeitpunkt aus unbekannten Gründen das Element nicht mehr hervorgehoben ist. Lösung vorerst ist die Abhängigkeit von diesem Highlighten zu entfernen.
