### ISSUE TITLE
Kopieren von alten Text und Headline SmartBlocks

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#706]
Wird ein alter Text oder Headline SmartBlock kopiert, der noch in einem MDE erstellt wurde, sollte dieser SmartBlock beim Kopiervorgang automatisch geupgraded werden.

**Comment by pmdevelopment** [comment]
Nicht mehr reporduzierbar, vermutlich verursacht durch #705
