### ISSUE TITLE
SmartTool Icon Library: Umsetzung

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#768]
Figma: https://www.figma.com/file/CGECvVk82F1ZMMEDIacMCx/Smart-Tools?node-id=793%3A1830&mode=dev

- [ ] Sortierung nach Aktualisiert / Name / Erstellungsdatum
- [ ] Filter nach Tags
- [ ] Volltextsuche
- [ ] Farbgruppen
- [ ] Multiple Icons wählbar
- [ ] Auflistung aller Icons; Pagination berechnen ohne Scroll
- [ ] Klick zur Aus/Abwahl eines Icons
- [ ] Auswahl des Icons zeigt Sidebar

## Farbgruppen

- [ ] Hauptfarbe wird in der Liste gezeigt
- [ ] Optionaler Namaler Namee
- [ ] Platzhalter-Icon

## Sidebar

- [ ] Tabs Export und Metadaten
- [ ] Metadaten mit Accordion der gewählten Icons
- [ ] Editor kann Metadaten direkt bearbeiten
- [ ] Export vergleichbar zum SmartBlock, zuzüglich Farbauswahl per Platzhalter-Icon

## Backend

- [ ] Hinzufügen von neuen Farbgruppen mit Name und Platzhalter Farbe
- [ ] Choice zur Zuordnung der Farben anhand im Platzhalter erkannter Werte

**Comment by ChristinaGu** [comment]
In Kunden Repo umgezogen
