### ISSUE TITLE
CKEditor Bullet Points: Verhalten bei zweizeiligen Aufzählungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#774]
Der Text richtet sich im Moment vertikal mittig mit dem Icon aus. Text und Icon sollten allerdings vertikal oben ausgerichtet sein. 
![a3142c01-ae28-4e5a-a375-a64898f8887d](https://github.com/wirDesign-communication-AG/wirhub-app/assets/8007132/a00e2213-cd4f-4ea6-87bb-9e16176632c9)

**Comment by pmdevelopment** [comment]
Wird als Teil von wirDesign-communication-AG/wirhub-customer-kws#8 online gehen
