### ISSUE TITLE
SmartBlock Icons: Download aller Icons funktioniert nicht

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#796]

**Comment by ChristinaGu** [comment]
Im Brandnet öffnet sich kurz der Dialog und man wird dann auf die Startseite weitergeleitet (ohne Download). Scheint also kein Serverspezifisches Problem zu sein.

**Comment by pmdevelopment** [comment]
Command scheitert mit folgendem Fehler:

    In IconListService.php line 155:
    
      Call to a member function getFile() on null

**Comment by pmdevelopment** [comment]
Wird in #810 behandelt
