### ISSUE TITLE
BVR wirHub updaten auf v3.0.16 um Internen Link in Text Bug zu fixen

### ISSUE THREAD

**Issue by neelebienzeisler** [wirDesign-communication-AG/wirhub-app#797]
Der wirHub vom BVR ist noch auf der v3.0.15 und ich kann keine internen Links in Text setzen. Auf den anderen Hubs mit neuerer Version geht das aber. Könnt ihr den Hub vom BVR auf v3.0.16 updaten, damit das Problem gefixt ist?

www.markenwelt.wegfrei-portal.de

**Comment by ChristinaGu** [comment]
Hi Neele, 
da es bei so einem Update zu einer kurzen Downtime kommen kann, kann ich das leider nicht mitten am Tag machen und würde mich morgen früh oder heute spät am Abend darum kümmern. 

LG

**Comment by ChristinaGu** [comment]
Ist jetzt auf 3.0.16
