### ISSUE TITLE
SmartBlock UI-Pattern: wirft Error 500

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#809]
siehe z.B. hier https://www.markenportal-versicherungskammer.de/versicherungskammer-bayern/style/category/basics

**Comment by pmdevelopment** [comment]
{"message":"Uncaught PHP Exception TypeError: \"AppBundle\\Controller\\Element\\SmartBlock\\PatternController::frame(): Argument #3 ($version) must be of type int, string given, called in /var/www/wirhub/vendor/symfony/http-kernel/HttpKernel.php on line 181\" at /var/www/wirhub/vendor/wirdesign-communication-ag/wirhub/Controller/Element/SmartBlock/PatternController.php line 183"
