### ISSUE TITLE
"Wiederherstellen"-Funktion: beim Aktivieren kommt man immer auf die Startseite

### ISSUE THREAD

**Issue by Kschneider94** [wirDesign-communication-AG/wirhub-app#846]
Auf der Seite bleiben. ~~Bei Version v3.0.18 funktioniert es.~~

- [x] Wiederherstellen
- [x] Benutzer-Ansicht
- [x] Benutzer-Ansicht aufheben

**Comment by pmdevelopment** [comment]
Ursache sind mal wieder die Header, muss wie das globale Kontakt-Formular überarbeitet werden.
