### ISSUE TITLE
SmartBlock Attachement: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#851]
- [x] Icon Shopping Basket in „Sammlung herunterladen“-Button einbauen
- [x] Drag & Drop Funktion für Items verschieben, wie bei Do/Don't
- [x] Download-Bestätigung ist Lizenzhinweis, bitte anpassen wie im Design
- [x] Lizenzhinweis im Textfeld vorausfüllen: "*Achtung!* Alle hier zum Download angebotenen Materialien sind urheberrechtlich geschützt und unterliegen bestimmten Lizenzen.” und Design anpassen (siehe Design)
- [x] Lizenz-Hinweis bei Download im View Mode mit Alert und ohne Checkbox (siehe Design)
- [x] Tooltip Spacing anpassen: spacing-m an allen Rändern

**Design**
https://www.figma.com/file/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?type=design&node-id=254%3A7929&mode=design&t=CNhzrnus4zqTbGJ1-1

**Comment by pmdevelopment** [comment]
Modal "Bearbeiten" wird in einen eigenen Task ausgelagert
