### ISSUE TITLE
SmartBlock Slideshow: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#852]
- [x] Bearbeiten-Stift aus Smart-Block-Toolbar entfernen

**Inline Toolbar Funktionen**
Slide hinzufügen
- [x] Links/rechts hochladen -> öffnet Finder/Explorer 
- [x] wenn eine Schnittstelle zu einer Mediendatenbank besteht Option "Links/Rechts aus Assets auswählen" geben und dann zugehöriges Modal öffnen **! Icons kommen Teilweise von Lisa als svg :)**
- [x] Slider automatisch abspielen
- [x] Reihenfolge ändern (nur anzeigen, wenn 2 oder mehr Slides vorhanden sind)

Reihenfolge ändern
- [x] Klick öffnet Modal (Details siehe Design, please)

**Item-Einstellungen**

- [x] Item-Einstellungen in Flyout mit "more-vert"- Icon packen (wie Do/Don't)
- [x] Option "Bild per Upload tauschen" (öffnet Finder/Explorer)
- [x] wenn eine Schnittstelle zu einer Mediendatenbank besteht Option "Asset auswählen" geben und dann zugehöriges Modal öffnen
- [x] Funktion Löschen ist auch da
- [x] Bildunterschrift hinzufügen mit Inline Edit, wie bei Bild

** Sonstiges **

- [x] Im SmartBlock News muss der Slider ausgetauscht werden.
- [x] Accordion JS zu BS5 wechseln
- [x] Fehlende Beschreibung beim anlegen eines neuen Sliders
- [x] Fehlende Beschreibung nach Löschen eines Slides

**Design**
https://www.figma.com/file/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?type=design&node-id=1312%3A813&mode=design&t=CNhzrnus4zqTbGJ1-1

**Comment by pmdevelopment** [comment]
[icons_slide_hinzufügen.zip](https://github.com/wirDesign-communication-AG/wirhub-app/files/14535544/icons_slide_hinzufugen.zip)
