### ISSUE TITLE
Textplatzhalter-Funktion in Text-Toolbar einbauen

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#904]
Die Platzhalter sollen über die Text-Toolbar eingefügt werden können.

- [x] Icon: data_object
- [x] Position: als letztes ( Design in Figma stimmt noch nicht mit Live Toolbar überein)
- [x] Auswahl über Flyout: 'Platzhalter „Vorname“ einsetzen' und 'Platzhalter „Nachname“ einsetzen'
- [x] wird automatisch an die Position des Cursors gesetzt

**Design**
https://www.figma.com/design/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?node-id=2446-4657&t=3JrKHGJXQVJqucWV-4

**Comment by pmdevelopment** [comment]
Platzhalter: Services/Feature/InlineEditService.php

Twig Filter zum Parsen: variable|parse_placeholders

**Comment by pmdevelopment** [comment]
Hier die Dokumentation zum CKEditor: https://help.wirhub.de/entwicklung/style/category/development#el_b6cf10745eda8_container

Für diesen Issue relevant ist die Variante "Im SmartBlock", die alternative Verwendung kann ignoriert werden.
