### ISSUE TITLE
SmartBlock HTML: defekt

### ISSUE THREAD

**Issue by Kschneider94** [wirDesign-communication-AG/wirhub-app#930]
<img width="1990" alt="Bildschirmfoto 2024-05-15 um 12 43 42" src="https://github.com/wirDesign-communication-AG/wirhub-app/assets/135986480/b692e14f-c0cb-425e-a99c-8c70b2ec78d1">

**Comment by pmdevelopment** [comment]
Wurde bereits anderweitig gelöst.
