### ISSUE TITLE
Inhalte im Akkordeon werden nicht gespeichert

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#956]
Wenn in einem Textmodul innerhalb des Akkordeons mehrere Links eingefügt werden, und einer nachträglich in einen Primary Button umgewandelt wird, werden die Änderungen nicht mehr gespeichert.
Aber komischerweise, im wD-Intranet, Helpdesk & HNR, aber nicht im wD-staging

Abfolge der Aktionen:
1. Hab Akkordeonelement eingefügt
2. In eine der Akkordeonseiten sollte ein Text rein, der Hyperlinks enthält.
3. Der erste Text hat seinen Hyperlink bekommen, bin raus aus dem Editiermodus gegangen, um zu prüfen. Hat funktioniert, bin wieder in den Editiermodus gegangen, um zweiten Text mit Link in die Akkordeonseite zu schreiben.
4. Bevor ich den zweiten Text angefangen habe zu schreiben, bin ich nochmal zum ersten gegangen und habe dort "primary Button" für den Hyperlink ausgewählt.
Danach hat das Akkordeon keine weiteren vorgenommenen Änderungen mehr gespeichert. Unabhängig davon, ob ich die primary Button Funktion aus oder an gemacht habe (selbst diese Änderung wurde nicht gespeichert)

**Comment by pmdevelopment** [comment]
Ursache: Beim Wechsel des Edit Toggle wird das Accordion neu geladen. Elemente im Accordion werden dabei nicht korrekt geladen.
