### ISSUE TITLE
Diverse Smartblocks: Upload-Overlay schließt nur nach manuellem Seiten-Reload

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#985]
Bei einigen Smartblocks, in denen man Dateien uploaden kann, bleibt das Ladescreen-Overlay dauerhaft offen, obwohl die Medien bereits als "Das Hochladen ist abgeschlossen" angezeigt werden. 

- [x] Anhang (siehe Screenshot) 
- [x] Slideshow
- [x] Do/Don't
- [x] Icons
- [x] Kapitelteaser (wenn man einen Kapitelteaser löscht)
- [x] Akkordeon

![Bildschirmfoto 2024-07-30 um 10 52 53](https://github.com/user-attachments/assets/80f70717-1533-43ad-9d65-64fa7bed7c32)

**Comment by pmdevelopment** [comment]
Für folgende SmartBlocks nachvollziehbar

- Do/Dont
- Icons
- Kapitelteaser
