### ISSUE TITLE
Smartblock Inhaltsverzeichnis: Ausgeblendete Überschrift wird trotzdem angezeigt

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#987]
Überschriften einer Seite, die durch den Nutzer ausgeblendet werden, tauchen trotzdem im Inhaltsverzeichnis auf der Seite aus (siehe Screenshot).

![Bildschirmfoto 2024-07-29 um 15 36 57](https://github.com/user-attachments/assets/73c1bcad-a9be-48c6-a2e2-3f013d3970c6)

**Comment by pmdevelopment** [comment]
Wird sie denn auch für einen normalen Nutzer angezeigt? Der Redakteur darf sie ja sehen, da ist das kein Bug

**Comment by lisaschreyer** [comment]
Ja Sven, den Hinweis hab ich von Katharina in der Zwischenzeit auch schon bekommen. Ticket kann weg :-)
