### ISSUE TITLE
Smartblock Bühne: Hintergrund- und Textfarbe

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#988]
- [ ] Aktuell ist die Hintergrundfarbe für die Bühne nur über die gesamte Breite möglich, nicht aber als Hintergrund innerhalb des Elements (also auf dem Bild, siehe Screenshot - gelber Hintergrund). 

- [ ] Beim Hinzufügen der Kapitelübersicht werden die eingefügten Kapitel nicht in der Textfarbe anzeigt, die für den Rest-Text hinterlegt ist (sieh Screenshot - lila). 

![Bildschirmfoto 2024-07-30 um 11 11 05](https://github.com/user-attachments/assets/1379f049-0916-43e2-949d-a0595deed922)

**Comment by ChristinaGu** [comment]
Wird angepasst, wenn Bühne überarbeitet wird. 
* Hintergrundfarbe ändert Farbe von grauem Hintergrund
* Textfarbe ändert Farbe von alles Texten (inklusive Links) und Link-Icon

Prio niedrig
