### ISSUE TITLE
SmartBlock Icons: Definition von zusätzlichen Feldern funktioniert nicht

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#996]
Schritte zur Reproduktion: 
1. Anlage eines neuen Smartblocks Icons
2. Hinzufügen eines zusätzlichen Feldes (siehe Screenshot "Name des Icons") 
3. Klick auf Hinzufügen > Fehlermeldung: Dieser Wert ist nicht gültig

![Bildschirmfoto 2024-08-06 um 09 22 27](https://github.com/user-attachments/assets/b8b52c6c-66c2-4b36-9a4b-21f24680869e)

**Comment by pmdevelopment** [comment]
Der Name darf afaik keine Leerzeichen enthalten, das ist eine technische Einschränkung die nicht ausreichend kommuniziert wird.

**Comment by Kschneider94** [comment]
Wenn man ein Zusatzfeld hinterlegt hat und dann ein Icon bearbeiten will, kommt ebenfalls eine Fehlermeldung:

![Bildschirmfoto 2024-10-08 um 13 50 10](https://github.com/user-attachments/assets/6fa08e86-84c3-4ba0-a470-0e2adbda8717)

**Comment by lisaschreyer** [comment]
Erweiterte Buglist vom Icon SmartBlock in Ticket #1120
