### ISSUE TITLE
Smartblock Kapitel Teaser: Interne Verlinkung und Zurück funktioniert nicht

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#998]
Schritte zur Reproduktion: 
1. Anlage Kapitel Teaser mit interner Verlinkung
2. Klick auf die Verlinkung > öffnet sich im selben Tab
3. Klick auf Zurück im Browser > die angelegte Kachel ist weg
4. Anlage einer neuen Kachel im Kapitelteaser > beide Kacheln sind plötzlich wieder sichtbar 

Wenn das Verhalten auftritt, klappt auch die eingestellte Hintergrundfarbe nicht.

**Comment by pmdevelopment** [comment]
Das ist inhaltlich ein Duplikat zum anderen Ticket über die zurück Funktion, das ist ein Problem des Browsers und die Lösung wird für alle SmartBlocks gelten

**Comment by lisaschreyer** [comment]
Dann schließe ich das andere Ticket und bündel beide hier
